### ISSUE TITLE
Error in if (is.na(window[[jj]])) { : the condition has length > 1 in Example

### ISSUE THREAD

**Issue by 1667857557** [LidaWangPSU/EXPRESSO#1]
Hi Dr.Wang

Thank you for your excellent work. We encountered an issue when running the example workflow. Could you provide some advice? Additionally, could you supply some information and code on how to generate the Whole_Blood_annotation_chr22.txt file and obtain 3D genomic or epigenomic information for input? Thanks in advance!

Best,
Huang

```
> refFile <- "gtex_chr22.hm3"
> annoFile <- "Whole_Blood_annotation_chr22.txt"
> sumstatFile<- "Whole_Blood_GTEx_hm3_chr22_sumstat_beta.txt"
> ##Find gene list##
> gene_subset = unique(read.table(sumstatFile, header = TRUE)$gene) 
> windowFile <- c( "Whole_Blood_1mb_chr22.txt",
+                  "Whole_Blood_250kb_chr22.txt",
+                  "Whole_Blood_loop_chr22.txt",
+                  "Whole_Blood_domain_chr22.txt",
+                  "Whole_Blood_tad_chr22.txt",
+                  "Whole_Blood_pchic_chr22.txt")
> out_path= "./EXPRESSO"
> res.tmp <- EXPRESSO(sumstatFile,annoFile,windowFile,refFile,out_path,minMaf=0.01,maxIter=1000,gene.vec = gene_subset,append=F)
Analysing ENSG00000100412 
Error in if (is.na(window[[jj]])) { : the condition has length > 1
```

**Comment by LidaWangPSU** [comment]
Hi Huang,

Thank you for using our package and for pointing out the issue. We have fixed the bug and tested it on our end. Please try running the sample code again and let me know if it works for you now.

For epigenetic annotation, you can obtain tissue/cell type-specific data from [SCREEN](http://screen.encodeproject.org/) or other annotation resources. The file "Whole_Blood_annotation_chr22.txt" includes all the SNPs you'll need. The first five columns ("snp", "chr", "pos", "ref", "alt") specify the SNP, and the sixth column, "overlap," indicates whether the SNP overlaps with an epigenetic annotation. You can assign a value of 1 to SNPs that overlap and 0 to those that do not.

For 3D genomic annotation, data is available from [3D Genome](http://3dgenome.org/). You can define a region (start and end position) for each gene based on your annotations.

Feel free to reach out if you have any other questions.

Best
Lida
