### ISSUE TITLE
warning message occurred when i ran EXPRESSO function

### ISSUE THREAD

**Issue by sugiYag** [LidaWangPSU/EXPRESSO#2]
Hi,

now i followed your tutorial in the example folder of this repository.

but the warning message occurred when I ran EXPRESSO code as follows :

Warning messages:
1: In mean.default(lambda_list[, which.min(colSums(bic))]) :
  argument is not numeric or logical: returning NA
2: In mean.default(lambda_list[, which.min(colSums(bic))]) :
  argument is not numeric or logical: returning NA

Thus, I would like to ask whether this warning poses any problem for the analysis or if I need to address it.

Thank you

**Comment by LidaWangPSU** [comment]
Hi, the warning will not influence the results. Best, Lida.
